### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#109]
- [x] Add travis badge to project readme #110
- [x] Allow for python 3 support for urlparse #113
- [x] Change to `api-root` from 301 to 302 #115 
- [x] Upgrade to factory boy 2.6 #117
- [x] Add django 1.8 security middleware to common.py #121
- [x] Upgrade to Django 1.9 #124
- [x] Remove Django-pnm #126
