### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#127]
- [x] Updated drf page number pagination settings #145
- [x] Upgrade user model `pk`s to `uuids` [#65](https://api.github.com/repos/agconti/cookiecutter-django-rest/issues/65)
- [x] For connivence, separate runserver from createsuperuser  [#140](https://api.github.com/repos/agconti/cookiecutter-django-rest/issues/140)
- [x] Add @python_2_unicode_compatible to models [#139](https://api.github.com/repos/agconti/cookiecutter-django-rest/issues/139)
- [x] Remove zeropush config from fab init #138
- [x] Use standard django-configurations once it releases `0.9` #63
- [x] Refactor settings to use Django class based settings instead of Django Configurations #118
- [x] Add .editorconfig file #101
- [x] Update dependencies #129
- [x] django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet #131
- [x] Heroku link is broken in ReadMe #135
- [x] Add django configurations to features list #133
