### ISSUE TITLE
Release 0.5.0 

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#148]
- [x] Remove duplicate append slash setting in `config/common` #162
- [x] Add .github folder and include issue and pull request templates #160
- [x] Remove django sites configuration since its not needed for rest apis #161
- [x] Update django template loaders settings #158
- [x] Scale heroku dynos to hobby tier #157
- [x] Add django-unique-upload for unique uploads with uuids #154
- [x] Set versatile image's field to 'create_images_on_demand' to false in production by default. #153
- [x] boto not add the Signature and Key to #152 
- [x] Set APPEND_SLASH to False #149
