### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#327]
- [x] Upgrade to Django 1.10 #328
- [x] Add auth password validators #253
- [x] Update manage.py with new django 1.10 content. #252
- [x] Update MIDDLEWARE_CLASSES setting to MIDDLEWARE #209
- [x] Update to Django 1.10 logging configuration #208
- [x] Update mkdocs to 0.16.1 #334
- [x] Update gevent to 1.2.0 #336
- [x] Update coverage to 4.3 #339
- [x] Update coverage to 4.3.1 #341
- [x]  Remove django-secure #356
- [x] Update gevent to 1.2.1 [#360](https://github.com/agconti/cookiecutter-django-rest/issues/360)
- [x] Update newrelic to 2.78.0.57 [#353](https://github.com/agconti/cookiecutter-django-rest/issues/353)
- [x] Update whitenoise to 3.2.3 [#352](https://github.com/agconti/cookiecutter-django-rest/issues/352)
- [x] Update django to 1.10.5  [#351](https://github.com/agconti/cookiecutter-django-rest/issues/351)
- [x] Update newrelic to 2.78.0.57 [#350](https://github.com/agconti/cookiecutter-django-rest/issues/350)
- [x] Update dj-database-url to 0.4.2 [#349](https://github.com/agconti/cookiecutter-django-rest/issues/349)
- [x] Update django-model-utils to 2.6.1 [#348](https://github.com/agconti/cookiecutter-django-rest/issues/348)
- [x] Import Error [#337](https://github.com/agconti/cookiecutter-django-rest/issues/337)
- [x] Update whitenoise to 3.3.0 [#363](https://github.com/agconti/cookiecutter-django-rest/issues/363)
- [x] Update markdown to 2.6.8 [#362](https://github.com/agconti/cookiecutter-django-rest/issues/362)
- [x] Update ipdb to 0.10.2 [#361](https://github.com/agconti/cookiecutter-django-rest/issues/361)
- [x] Update djangorestframework to 3.5.4 [#372](https://github.com/agconti/cookiecutter-django-rest/issues/372)
- [x] Update flake8 to 3.3.0 [#371](https://github.com/agconti/cookiecutter-django-rest/issues/371)
- [x] Update ipython to 5.2.2 [#369](https://github.com/agconti/cookiecutter-django-rest/issues/369)
- [x] Update djangorestframework to 3.5.4 [#374](https://github.com/agconti/cookiecutter-django-rest/issues/374)
- [x] Update flake8 to 3.3.0 [#373](https://github.com/agconti/cookiecutter-django-rest/issues/373)
- [x] Update django-versatileimagefield to 1.6.3 #376
- [x] Update boto to 2.46.1 #379
- [x] Staticfiles dirs is a list of lists #386
- [x] Update psycopg2 to 2.7 [#384](https://github.com/agconti/cookiecutter-django-rest/issues/384)
- [x] Update django to 1.10.6 [#383](https://github.com/agconti/cookiecutter-django-rest/issues/383)
- [x] Update newrelic to 2.80.1.61 [#382](https://github.com/agconti/cookiecutter-django-rest/issues/382)
- [x] Update ipython to 5.3.0 [#381](https://github.com/agconti/cookiecutter-django-rest/issues/381)
- [x] Update gunicorn to 19.7.0 #387
- [x] Update django-rq to 0.9.5 #394
- [x] Update newrelic to 2.82.0.62 #395
- [x] Update mkdocs to 0.16.2 #393
- [x] Update psycopg2 to 2.7.1 #392
- [x] Update djangorestframework to 3.6.2 #391
- [x] Update django-model-utils to 3.0.0 [#402](https://github.com/agconti/cookiecutter-django-rest/issues/402)
- [x] Update mkdocs to 0.16.3 [#401](https://github.com/agconti/cookiecutter-django-rest/issues/401)
- [x] Update django to 1.11 [#400](https://github.com/agconti/cookiecutter-django-rest/issues/400)
- [x] Update pytz to 2017.2 [#398](https://github.com/agconti/cookiecutter-django-rest/issues/398)
- [x] Update django-filter to 1.0.2 [#397](https://github.com/agconti/cookiecutter-django-rest/issues/397)
- [x] Update gunicorn to 19.7.1 [#396](https://github.com/agconti/cookiecutter-django-rest/issues/396)
- [x] Update ipython to 6.0.0 #407- [ ] Update newrelic to 2.86.0.65 [#411](https://github.com/agconti/cookiecutter-django-rest/issues/411)
- [x] Update fabric to 1.13.2 [#409](https://github.com/agconti/cookiecutter-django-rest/issues/409)
- [x] Update ipdb to 0.10.3 [#408](https://github.com/agconti/cookiecutter-django-rest/issues/408)
- [x] Update django-versatileimagefield to 1.7.0 [#406](https://github.com/agconti/cookiecutter-django-rest/issues/406)
- [x] Update django-filter to 1.0.4 [#420](https://github.com/agconti/cookiecutter-django-rest/issues/420)
- [x] Update newrelic to 2.86.1.66 [#419](https://github.com/agconti/cookiecutter-django-rest/issues/419)
- [x] Update coverage to 4.4.1 [#417](https://github.com/agconti/cookiecutter-django-rest/issues/417)
- [x] Update djangorestframework to 3.6.3 [#415](https://github.com/agconti/cookiecutter-django-rest/issues/415)

**Comment by auvipy** [comment]
is this going to happen anytime soon?

**Comment by agconti** [comment]
Hey @auvipy, these release's are just milestone trackers and a tool for organizing the project. Features merged into master are live.

**Comment by auvipy** [comment]
cool! thanks
