### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#4]
- [x] Update users app with the appropriate test cases #1 
- [x] Add api docs for user app #2
- [x] add tests for auth tokens #43
- [x] Add api docs for auth #3 
- [x] Add django-storages-redux config to production. #6
- [x] Handle "/" routing #7
- [x] add redis to app readme prerequisites. #9
- [x] Upgrade mkdocs to 0.14.0 #10 
- [x] Add `git init` to project ReadMe #17
- [x] Update pg backups with schedule time #18
- [x] Migrate the database after deploys #19
- [x] add fab dev and qa tasks back in #20
- [x] Update docs index to include readme #27
- [x] Update flake8 fab task to target project dir #30
- [x] Exclude migrations from flake8 #31
- [x] Configure nosetests arguments #32 
- [x] Update flake8 to allow for easy debugging #37
- [x] Add faker for mocking #41
- [x] Remove email notifications from travis #48
- [x] Update cookie cutter params to specify username / **organization name** #47
- [x] Add github username to heroku repo deploy #46
- [x] Update app routing to use a single DefaultRouter #45
- [x] Exclude mkdocs site dir via gitignore #52
- [x] Update django-pnm to 0.1.5 #54
- [x] Update Authentication docs to include obtain `auth_token` endpoint #56
- [x] Add caching via django-redis to features list #58
- [x] Update ReadMe with more detailed background on project #60
- [x] Upgrade to Django 1.8 after django-configurations has been upgraded. #8
- [x] Add gif of scaffolding to ReadMe #66 
- [x] Fix broken heroku run command #71 
- [x] Database values are not set in Travis file #69
- [x] Running ./manage.py test will result in "Coverage.py warning: Module walc was never imported." #67
- [x] Tests should have `--nologcapture` added to the NOSE_ARGS #77
- [x] Add `contributing.md` #74
- [x] RelatedObjectDoesNotExist: User has no auth_token. #75
- [x] Configure Django template debug settings #82
- [x] Update to DRF 3.2.3 #81
- [x] Update to Django 1.8.4 #80
- [x] Upgrade Django-pnm to 1.6 #86
- [x] Update `RedirectView.permanent` to true for `api-root` route #90
- [x] Upgrade dependencies #89 
- [x] Update `.travis` postgres config #88
- [x] Add `.coveragerc` #73
