### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#40]
- [x] Update heroku postgresql addon config #98
- [x] Fix fabfile spacing #103
- [x] Do super() in test case of users #106
- [x] Remove auth_token from UserSerializer #104
- [x] Set up automated testing via travis #107
