### ISSUE TITLE
Release 0.8.0

### ISSUE THREAD

**Issue by agconti** [agconti/cookiecutter-django-rest#468]
- [x] Upgrade to Django 2.0 #505
- [x] Fully Dockerize app #325 
- [x] Update ReadMe overview to be more descriptive #470
- [x] Remove IA Diagram from README #469
- [x] Add code of conduct to repo #473 
- [x] cannot connect to postgres db [#450](https://github.com/agconti/cookiecutter-django-rest/issues/450)
- [x] fab init:  [#425](https://github.com/agconti/cookiecutter-django-rest/issues/425)
- [x] Nose not picking up tests [#416](https://github.com/agconti/cookiecutter-django-rest/issues/416)
- [x] Add users app config. Rename models.py to signals.py [#414](https://github.com/agconti/cookiecutter-django-rest/issues/414)
- [x] Fix python3 print statements [#388](https://github.com/agconti/cookiecutter-django-rest/issues/388)
- [x] CORS  [#364](https://github.com/agconti/cookiecutter-django-rest/issues/364)
